Fix/refactor tracker
microsoft/electionguard-cpp pull request #165
Opened 2021-03-30 21:58 UTC by AddressXception

_🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository._

### Issue
*Link your PR to an issue*
partial #163 

https://github.com/microsoft/electionguard-python/issues/322

Fixes #___

### Description
just the tracking code

### Testing
Run the tests

2021-03-31 14:09 UTC, keithrfung requested changes
The most notable fix is `InternalElectionDescription` reference, but a couple other small things.

2021-03-31 14:09 UTC, keithrfung commented on src/electionguard/facades/ballot_code.cpp
> +eg_ballot_code_get_rotating_ballot_code(eg_element_mod_q_t *in_previous, uint64_t in_timestamp,
This should be changed and the `rotating` word should be removed.

2021-03-31 14:09 UTC, keithrfung commented on src/electionguard/facades/encrypt.cpp
>          auto *metadata = AS_TYPE(InternalElectionDescription, in_metadata);
Another reference to Internal Election Description

2021-03-31 14:09 UTC, keithrfung commented on src/electionguard/facades/encrypt.cpp
>          auto *metadata = AS_TYPE(InternalElectionDescription, in_metadata);
InternalElectionDescription again.

2021-03-31 14:09 UTC, keithrfung commented on test/electionguard/test_words.cpp
> +        auto secondRotatingHash =
The use of rotating hash here should likely get removed. Implies chaining.

2021-03-31 14:15 UTC, AddressXception commented on bindings/netstandard/ElectionGuard/ElectionGuard.Shared/Encrypt.cs
> +            InternalElectionDescription internalManifest,
next pr

2021-03-31 14:16 UTC, AddressXception commented on bindings/netstandard/ElectionGuard/ElectionGuard.Shared/NativeInterface.cs
> +            //     ContestDescription.InternalElectionDescriptionHandle metadata,
next pr

2021-03-31 17:24 UTC, AddressXception commented on test/electionguard/mocks/words.cpp
> +    EG_API string hashToWords(const ElementModQ &trackerHash, const char *separator)
i just deleted the files.  theyll be in history if we need them

2021-04-02 15:28 UTC, rc-ms commented on test/electionguard/mocks/words.cpp
> +    EG_API string hashToWords(const ElementModQ &trackerHash, const char *separator)
no worries we can reconstitute later if need be

2021-04-02 20:52 UTC, keithrfung approved these changes

2021-04-06 13:41 UTC, merged